### ISSUE TITLE
Can't run train_predict.py

### ISSUE THREAD

**Issue by 0xyangl** [yuanyao366/PRP#9]
Can't run the train_predict.py, after i download the whole file and the datasets, then when i tried to run train_predict.py it stopped.
![image](https://user-images.githubusercontent.com/71805758/184827101-eaf1e560-610f-4833-a07a-9bbabea99674.png)
Is there anything that i do it wrong? Thanks 👍

**Comment by 0xyangl** [comment]
this is the main file![image](https://user-images.githubusercontent.com/71805758/184843845-2386653b-5ddd-46cd-8e48-f879004d8720.png)
i created a folder named "split" with testlist01 and put it into UCF-101 file
![image](https://user-images.githubusercontent.com/71805758/184844237-3d88299d-b422-423d-8041-ef25be840bdd.png)

**Comment by 0xyangl** [comment]
目前測試從 train_predict.py 第292行
![image](https://user-images.githubusercontent.com/71805758/184845762-275bcbbf-e5c6-4f69-bd7f-024329bdf61c.png)
呼叫PredictDataset進入到predict_dataset.py後 運行到 第66行 後predict_dataset.py就卡住沒有運作了 
![image](https://user-images.githubusercontent.com/71805758/184845716-c5a52f75-34de-4b09-9756-4af1fbe3cd50.png)
train_predict.py 則是跑到337行 進入到train才卡住的
![image](https://user-images.githubusercontent.com/71805758/184845681-fb30f48d-12dc-49d9-856c-def621a905c6.png)
進入train()後 運行到第100行要進入for迴圈之後就卡住了
![image](https://user-images.githubusercontent.com/71805758/184845632-2e173b04-e175-4350-88a1-e88f9e3f37c6.png)

**Comment by 0xyangl** [comment]
Sorry i'm a student so i might ask some easy question

**Comment by 0xyangl** [comment]
i found out that in predict_dataset.py 
![image](https://user-images.githubusercontent.com/71805758/184863982-0e54325b-068b-404f-817f-85dbb2d77bf8.png)
the fram_count always gets 0, so it can not break out the while loop. 
![image](https://user-images.githubusercontent.com/71805758/184864661-15fbe756-3e60-4d82-be46-ba592ffe9e8c.png)

**Comment by yuanyao366** [comment]
Can the "cv2.VideoCapture(fname)" in line 130 of predict_dataset.py load the video correctly? It seems that the video is not loaded, resulting in  frame_count = 0.

**Comment by 0xyangl** [comment]
![image](https://user-images.githubusercontent.com/71805758/184899158-9d513815-3c22-48b0-af6a-623eddf1db0b.png)
After I changing the path of the UCF-101 to 
![image](https://user-images.githubusercontent.com/71805758/184899566-db676683-8d5b-4674-a6cb-a54c8f153b7f.png)
the code start working! Thank you so much for helping me solving the problem!

**Comment by 0xyangl** [comment]
Thanks for helping 👍
